apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: rps  
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/target: "8"
    spec:
      containerConcurrency: 4
      containers:
      - image: gcr.io/knative-samples/autoscale-go:0.1
