apiVersion: samples.knative.dev/v1alpha1
kind: BrokerChannel
metadata:
  name: knative-svc-motion
  namespace: default
spec:
  brokeraddr: 10.244.1.61
  brokerport: 1883
  topic: motion
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: helloworld-go